CREATE TABLE test (
  id     INTEGER      NOT NULL PRIMARY KEY AUTOINCREMENT,
  field1 VARCHAR(255) NOT NULL,
  field2 VARCHAR(255) NOT NULL
);

CREATE TABLE test_join (
  id         INTEGER      NOT NULL PRIMARY KEY AUTOINCREMENT,
  field1     VARCHAR(255) NOT NULL,
  someField2 VARCHAR(255) NOT NULL,
  testId     INTEGER      NOT NULL,
  FOREIGN KEY (testId_fky) REFERENCES test (id)
);
